import { Container, Heading, Text } from "@radix-ui/themes"

const Accueil = () => {

    return (
        <Container>
            <Heading as="h1">Accueil</Heading>
            <Text as="p">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique ducimus vero culpa debitis? Doloremque, officia modi. Sit ipsa ratione quaerat veniam tempora iusto illum amet necessitatibus illo rem corrupti natus at et nihil explicabo recusandae nisi, sed eaque? Et doloribus animi sit molestias, ut possimus voluptatum sunt architecto labore facilis. Dolor ipsam explicabo saepe maiores similique beatae quos sunt eius ex, molestias excepturi esse atque cum suscipit error provident, accusamus eaque amet corrupti ipsa minus. Harum ratione et nisi consectetur. Corrupti quis explicabo, quam vel dolores officiis laboriosam assumenda quasi, voluptatem minima autem debitis? Exercitationem deserunt incidunt voluptate quisquam, id dolore perspiciatis commodi officiis, aliquid odit nemo vel earum nihil, dolorum repellendus eum rem tempore voluptates? Non quae beatae, ullam cumque sit amet a minus atque voluptatum sint eveniet vitae nobis placeat sequi quia odit excepturi provident suscipit officiis inventore laboriosam? Perferendis quo quaerat, accusamus saepe dolores ipsam. Officiis natus aliquid, fugiat culpa quis numquam aliquam? Consectetur, velit sequi! Ipsum iusto nostrum excepturi eaque aperiam cupiditate, veniam aliquid, culpa repellendus accusamus soluta ex neque nesciunt consectetur modi cum quaerat deserunt eius sunt obcaecati ut. Dicta totam sequi numquam minima consectetur alias vitae dolor dignissimos qui ab. Minus omnis neque voluptatem.</Text>
            <Text as="p">Delectus culpa laudantium quae, provident dignissimos earum porro consectetur natus sapiente placeat accusamus pariatur neque cumque ullam minima, nobis eius aliquam, praesentium iure? Nemo vitae error exercitationem esse laboriosam earum enim excepturi autem ratione necessitatibus, consequatur dolorum incidunt accusantium magnam consequuntur aliquam quaerat in ab. Id, reiciendis nulla velit quis sed nemo expedita impedit cum? Ea hic sint nulla! Eligendi facere quibusdam totam excepturi quae omnis rem doloribus sequi quidem culpa adipisci voluptas laudantium, iure, voluptate consequatur placeat nemo tempore fugiat in, ea asperiores. Vel, tenetur! Rem nostrum voluptatem id iusto sunt a ad facilis suscipit culpa quibusdam odio, distinctio enim, hic illo. Voluptatum eos, dicta reprehenderit rerum est error perspiciatis ipsum minima voluptatem ipsa ipsam itaque obcaecati possimus deleniti delectus quos facere tempora nam nemo ea rem molestias! Modi minus sit laudantium explicabo, distinctio beatae aut cupiditate voluptatibus eveniet deleniti, assumenda soluta quo iusto exercitationem tempora! Tempora iure nemo doloremque repellendus. Quasi optio consequuntur ipsa iste similique et vitae ea, harum libero nesciunt modi fugiat! Obcaecati, nisi dolore porro suscipit praesentium dignissimos ab corrupti soluta cumque autem. Placeat itaque dolore nesciunt fuga corrupti? Ullam tempore officiis eius hic veniam quod, nam sed aperiam placeat fugit quas, cupiditate, quaerat culpa.</Text>
            <Text as="p">Eaque, cupiditate hic pariatur et fuga adipisci minima quisquam itaque sapiente tempora nulla exercitationem porro accusamus cumque, unde, eum commodi ea odio. Natus harum laboriosam ipsum laborum pariatur laudantium ex impedit a, tenetur dolorum ut necessitatibus molestiae cumque quisquam. Dicta ullam vero cum possimus doloremque, vitae iure deleniti ex porro sapiente architecto, animi rerum aliquam. Ullam corrupti et totam enim minima, quas maiores dolorem fugiat cum perferendis reprehenderit voluptatum dolores, id esse perspiciatis quasi tenetur consequatur! Earum cumque nihil impedit quas. Ut porro amet corporis facere adipisci reprehenderit quaerat sed, nisi, veritatis consequuntur accusamus modi non expedita repellat autem nulla voluptatibus asperiores! At quae harum eum officia, officiis possimus facilis exercitationem aperiam ad ducimus expedita veniam voluptatibus quo! Veniam dolor illo quis, ut debitis exercitationem mollitia a quos dolore necessitatibus magni distinctio veritatis aliquam quidem expedita iusto architecto? Perspiciatis vitae sunt delectus quam possimus voluptas necessitatibus cumque numquam eum! Earum, obcaecati, praesentium illum dignissimos ab alias necessitatibus impedit similique modi dolores neque totam facilis eos est placeat omnis? Harum aperiam et at ullam sed. Ea nostrum sunt soluta id reprehenderit amet aliquam accusamus quaerat. Eligendi similique, voluptatibus enim expedita quaerat ipsa assumenda nesciunt esse aperiam natus eum quis vel. Facilis!</Text>
            <Text as="p">Laboriosam distinctio culpa dicta, officiis, necessitatibus fugiat dolores voluptas animi esse, minus earum! Alias tenetur delectus, nihil iusto placeat architecto. Dolore suscipit repellat dignissimos culpa laudantium fugit in repellendus accusamus delectus et voluptatem sapiente exercitationem nobis, sequi doloribus quaerat quos neque ad ratione numquam eveniet quasi atque. Labore vel tempore sit laborum facere illum deserunt tempora corporis nulla! Pariatur quisquam, modi sunt totam non porro delectus itaque odio asperiores optio laudantium voluptas aliquid quia quidem nesciunt quas ullam repudiandae, cumque in placeat vero, incidunt veritatis tenetur sit? Animi adipisci veniam officiis, modi nihil, soluta vero maxime voluptates quidem laborum natus suscipit non vitae repellat perspiciatis dolore, aut dignissimos architecto similique? Tenetur odit adipisci, ad repudiandae nemo doloremque corrupti officia voluptatum repellendus labore? Eligendi eos incidunt cum blanditiis quos dolorum! Illo, totam adipisci nemo perferendis, quaerat eligendi et maiores ducimus dicta, ipsam obcaecati quia aliquid? Culpa, totam magnam temporibus quis ipsam tempora modi cum, suscipit quod, voluptatem dolor. Libero minima fugiat maxime? Quisquam ab cumque doloremque facilis praesentium sed, tempora minus rerum nesciunt nihil, odit rem dolores molestiae vero commodi iusto? Debitis quae ducimus earum alias laborum et neque at explicabo inventore, vero rerum nemo dolores in! Natus totam corrupti hic.</Text>
        </Container>
    )
}

export default Accueil